### ISSUE TITLE
Deal with failed message

### ISSUE THREAD

**Issue by mehran-prs** [liftbridge-io/go-liftbridge#102]
How do you handle failed messages? I can not see a feature to send __nack__

**Comment by tylertreat** [comment]
Liftbridge does not have a notion of acking (or nacking) since it's not a message queue but rather an append-only log. There is, however, an [API that allows consumers to store cursors](https://liftbridge.io/docs/cursors.html) so that they can checkpoint positions in the log and resume consumption. In the future, consumer groups will extend this to make checkpointing more transparent to users.

In the case of a failed message, the consumer would need to update its position in the log to account for the message.

**Comment by mehran-prs** [comment]
Thanks @tylertreat, Right
I think we have multiple options in case of a failed message (let's say due to a source code bug DB error... ):
- __update cursor's position__: so we should process messages idempotent to skip next processed messages.
- __Dead Letters queue__: send message to dead letters queue after multiple retries(change offset to retry the process).

I need to know what should we do in production in case of error, so what do you think? this is what you do in your apps?

**Comment by mehran-prs** [comment]
Thanks @tylertreat
