### ISSUE TITLE
durable load balanced stream?

### ISSUE THREAD

**Issue by justinrush** [liftbridge-io/go-liftbridge#112]
One use case I have for liftbridge is a scale out pub/sub model I can use to load balance across a backend (similar to typical rabbitMQ use cases).  The documentation for liftbridge and the SDK documentation seem to indicate that having a load balanced group listening on the same stream is possible, but I can't figure out how that is done. The closest I've seen is the SetCursor option, but that doesn't appear to be implemented in the client returned by Connect.

It looks like there is something called an ActivityStream that was recently introduced into liftbridge, but not available in the go API. Is that something that accomplishes what I'm looking for and I just need to patiently wait?

**Comment by tylertreat** [comment]
A load-balance group is a set of streams that receive messages from a NATS subject in round-robin fashion. This is done by creating multiple streams with the same subject and using the `Group` option with the same name. You could use this pattern to balance messages amongst a set of consumers.

**Comment by justinrush** [comment]
> A load-balance group is a set of streams that receive messages from a NATS subject in round-robin fashion. This is done by creating multiple streams with the same subject and using the `Group` option with the same name. You could use this pattern to balance messages amongst a set of consumers.

But the Publish API requires that you send to a stream name and not a nats subject?

Provided I'm reading the wrong thing and I need to call something else, how does the consumer checkpoint so Liftbridge knows that the message was successfully delivered?

**Comment by tylertreat** [comment]
Yeah, that is correct. It's more meant for the NATS layer, i.e. publishing with NATS clients to NATS subjects, rather than the Liftbridge stream layer. This probably needs to be documented better.

If you are working only at the streams layer, the better approach might be to use a single stream that is partitioned, then have a single consumer for each partition which checkpoints it's position. This pattern will become a lot more seamless with once [consumer groups](https://liftbridge.io/docs/roadmap.html#consumer-groups-46httpsgithubcomliftbridge-ioliftbridgeissues46) are available.

**Comment by justinrush** [comment]
OK, i'll check back in a few months then, thanks
