### ISSUE TITLE
Query - using Liftbridge alongside NATS

### ISSUE THREAD

**Issue by asimpatnaik** [liftbridge-io/go-liftbridge#6]
Hi,
We have a publisher & subscriber developed using NATS (at most once delivery). I came across Liftbridge and read that we can use the existing NATS implementation for ensuring at least once delivery without much code change. It will be great if you can provide a sample for the same.

Regards,
Asim.

**Comment by tylertreat** [comment]
Yes, I will create some more examples for documentation. The idea behind Liftbridge is it's used to create durable streams attached to NATS subjects, so that when a message is published to the NATS subject, it's recorded to the stream. Subscribers which want at-least-once delivery then consume via the Liftbridge stream. Example: https://github.com/liftbridge-io/go-liftbridge#example

**Comment by tylertreat** [comment]
I've added more examples to the [README](https://github.com/liftbridge-io/go-liftbridge#basic-usage). Hope this helps!
